services:
  - type: web
    name: fastapi-server
    runtime: python
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString
